//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthShoreSurfApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthShoreSurfApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add events to carpool event.
        /// </summary>
        internal static string could_not_add_events_to_carpool_event {
            get {
                return ResourceManager.GetString("could_not_add_events_to_carpool_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add events to carpool request.
        /// </summary>
        internal static string could_not_add_events_to_carpool_request {
            get {
                return ResourceManager.GetString("could_not_add_events_to_carpool_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not answer confirmation.
        /// </summary>
        internal static string could_not_answer_confirmation {
            get {
                return ResourceManager.GetString("could_not_answer_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create carpool event.
        /// </summary>
        internal static string could_not_create_carpool_event {
            get {
                return ResourceManager.GetString("could_not_create_carpool_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create carpool request.
        /// </summary>
        internal static string could_not_create_carpool_request {
            get {
                return ResourceManager.GetString("could_not_create_carpool_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete invite.
        /// </summary>
        internal static string could_not_delete_invite {
            get {
                return ResourceManager.GetString("could_not_delete_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not invite passenger.
        /// </summary>
        internal static string could_not_invite_passenger {
            get {
                return ResourceManager.GetString("could_not_invite_passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign up to carpool event.
        /// </summary>
        internal static string could_not_sign_up_to_carpool {
            get {
                return ResourceManager.GetString("could_not_sign_up_to_carpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not unsign from carpool event.
        /// </summary>
        internal static string could_not_unsign_from_carpool {
            get {
                return ResourceManager.GetString("could_not_unsign_from_carpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist.
        /// </summary>
        internal static string user_already_exist {
            get {
                return ResourceManager.GetString("user_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
    }
}
